### PR TITLE
Updating project, making it up-to-date

### PR DESCRIPTION
**Pull request by sairam4123**
### Checklist

- [x] If code changes were made then they have been tested.
    - [x] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [x] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by sairam4123** [comment]
Can I update the project?, feel free to close this PR, I should have asked first, sorry!

**Comment by imayhaveborkedit** [comment]
Even if i wanted to, this pr has merge conflicts.  I need to rewrite anyways to match the new VoiceProtocol api and trim down the scope.

**Comment by sairam4123** [comment]
Yeah, I am sorry, but just fix the Overwrites issue. I tried joining both repos, and I am getting OpusNotLoaded error now.

**Comment by sairam4123** [comment]
And well, please provide the discord name, thank you.

**Pull request closed without merging**
